=== pinax-network/supported-networks/public/TheGraphNetworksRegistrySchema_v0_2.json
{
  "$id": "https://thegraph.com/schemas/registry.schema.json",
  "$schema": "http://json-schema.org/schema#",
  "title": "The Graph networks registry",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "minLength": 10,
      "format": "uri",
      "description": "Reference to this schema file"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$",
      "description": "Version of the registry"
    },
    "updatedAt": {
      "type": "string",
      "format": "date-time",
      "description": "Date and time of the last update"
    },
    "networks": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Network"
      },
      "description": "List of networks"
    }
  },
  "required": [
    "networks",
    "title",
    "description",
    "updatedAt",
    "version",
    "$schema"
  ],
  "additionalProperties": false,
  "$defs": {
    "Network": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^(?!-)[a-z0-9-]{3,}(?<!-)$",
          "description": "Established name of the chain on the Graph network, i.e. mainnet, btc, arweave-mainnet, near-testnet"
        },
        "shortName": {
          "type": "string",
          "description": "Short display name of the network, i.e. Ethereum, BNB"
        },
        "fullName": {
          "type": "string",
          "description": "Display name of the network, i.e. Ethereum Mainnet, Bitcoin Testnet"
        },
        "caip2Id": {
          "type": "string",
          "pattern": "^[-a-z0-9]{3,8}:[-_a-zA-Z0-9]{1,32}$",
          "description": "CAIP-2 Chain ID, i.e. eip155:1, bip122:000000000019d6689c085ae165831e93"
        },
        "newField": {
          "type": "string",
          "description": "dummy test field"
        },
        "aliases": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^(?!-)[a-z0-9-]{3,}(?<!-)$"
          },
          "description": "[optional] List of possible aliases for the chain id, i.e. ethereum, eth, mainnet, eth-mainnet"
        },
        "networkType": {
          "type": "string",
          "enum": [
            "mainnet",
            "testnet",
            "devnet"
          ],
          "description": "Whether the chain is a mainnet/testnet/devnet"
        },
        "relations": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "kind": {
                "type": "string",
                "enum": [
                  "testnetOf",
                  "beaconOf",
                  "forkedFrom",
                  "l2Of",
                  "shardOf",
                  "evmOf",
                  "other"
                ],
                "description": "Kind of relation"
              },
              "network": {
                "type": "string",
                "pattern": "^[a-z0-9-]+$",
                "description": "Id of the related network, i.e. mainnet, near-mainnet"
              }
            },
            "required": [
              "kind",
              "network"
            ],
            "additionalProperties": false
          }
        },
        "firehose": {
          "type": "object",
          "properties": {
            "blockType": {
              "type": "string",
              "pattern": "^[a-zA-Z0-9.]+$",
              "description": "Block type, i.e. sf.ethereum.type.v2.Block"
            },
            "bytesEncoding": {
              "type": "string",
              "enum": [
                "hex",
                "0xhex",
                "base58"
              ],
              "description": "Bytes encoding, i.e. hex, 0xhex, base58"
            },
            "bufUrl": {
              "type": "string",
              "format": "uri",
              "description": "Protobuf definitions on buf.build, i.e. https://buf.build/streamingfast/firehose-ethereum"
            },
            "evmExtendedModel": {
              "type": "boolean",
              "description": "[optional] Whether supports extended block model if EVM chain"
            }
          },
          "required": [
            "blockType",
            "bytesEncoding",
            "bufUrl"
          ],
          "additionalProperties": false,
          "description": "Firehose block information"
        },
        "genesis": {
          "type": "object",
          "properties": {
            "hash": {
              "type": "string",
              "description": "Hash of the genesis block either in 0x-prefixed hex or base58",
              "pattern": "^(0x[a-fA-F0-9]+|[1-9A-HJ-NP-Za-km-z]+)$"
            },
            "height": {
              "type": "integer",
              "description": "Block height of the genesis or the first available block",
              "minimum": 0
            }
          },
          "required": [
            "hash",
            "height"
          ],
          "additionalProperties": false
        },
        "nativeToken": {
          "type": "string",
          "pattern": "^[a-zA-Z0-9]+$",
          "description": "Symbol of the native token"
        },
        "graphNode": {
          "type": "object",
          "properties": {
            "protocol": {
              "type": "string",
              "enum": [
                "ethereum",
                "near",
                "arweave",
                "cosmos",
                "starknet"
              ],
              "description": "[optional] Protocol name in graph-node, i.e. ethereum, near, arweave"
            }
          }
        },
        "explorerUrls": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uri"
          },
          "description": "URLs for the block explorers"
        },
        "support": {
          "type": "object",
          "properties": {
            "subgraphs": {
              "type": "array",
              "items": { "$ref": "#/$defs/Network/$defs/Service" }
            },
            "sps": {
              "type": "array",
              "items": { "$ref": "#/$defs/Network/$defs/Service" }
            },
            "firehose": {
              "type": "array",
              "items": { "$ref": "#/$defs/Network/$defs/Service" }
            },
            "substreams": {
              "type": "array",
              "items": { "$ref": "#/$defs/Network/$defs/Service" }
            }
          },
          "description": "Providers support for the chain by providers"
        },
        "issuanceRewards": {
          "type": "boolean",
          "description": "Issuance rewards on the Graph Network for this chain"
        },
        "web3Icon": {
          "type": "string",
          "pattern": "^[a-z0-9-]+$"
        },
        "rpcUrls": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uri-template"
          },
          "description": "List of RPC URLs for the chain. Use {CUSTOM_API_KEY} as a placeholder for a private API key"
        },
        "apiUrls": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string",
                "format": "uri-template"
              },
              "kind": {
                "type": "string",
                "enum": [
                  "etherscan",
                  "blockscout",
                  "ethplorer",
                  "subscan",
                  "other"
                ]
              }
            },
            "required": [
              "url",
              "kind"
            ],
            "additionalProperties": false
          },
          "description": "List of API URLs for the chain, i.e. https://api.etherscan.io/api. Use {CUSTOM_API_KEY} as a placeholder for a private API key"
        },
        "docsUrl": {
          "type": "string",
          "format": "uri",
          "description": "URL to the chain documentation"
        },
        "indexerDocsUrls": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string",
                "format": "url"
              },
              "kind": {
                "type": "string",
                "enum": [
                  "rpc",
                  "firehose",
                  "other"
                ]
              },
              "hint": {
                "type": "string"
              }
            },
            "required": [
              "url",
              "kind"
            ],
            "additionalProperties": false
          },
          "description": "Documentation to run indexer components for the chain"
        }
      },
      "required": [
        "id",
        "caip2Id",
        "shortName",
        "fullName",
        "networkType",
        "support",
        "issuanceRewards"
      ],
      "additionalProperties": false,
      "$defs": {
        "Service": {
          "type": "object",
          "properties": {
            "provider": {
              "type": "string",
              "enum": [
                "e&n",
                "pinax",
                "graphops",
                "streamingfast",
                "messari",
                "semiotic"
              ]
            },
            "url": {
              "type": "string",
              "format": "uri"
            }
          },
          "required": ["provider"],
          "additionalProperties": false
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "caip2Id": {
                "type": "string",
                "pattern": "^eip155:"
              }
            }
          },
          "then": {
            "properties": {
              "firehose": {
                "type": "object",
                "properties": {
                  "evmExtendedModel": {
                    "type": "boolean"
                  }
                },
                "required": ["evmExtendedModel"]
              },
              "graphNode": {
                "type": "object",
                "properties": {
                  "protocol": {
                    "const": "ethereum"
                  }
                }
              }
            }
          },
          "else": {
            "properties": {
              "firehose": {
                "type": "object",
                "properties": {
                  "evmExtendedModel": {
                    "const": false,
                    "description": "evmExtendedModel makes no sense for non-EVM chains"
                  }
                }
              },
              "graphNode": {
                "type": "object",
                "properties": {
                  "protocol": {
                    "anyOf": [
                      { "not": { "const": "ethereum" } },
                      { "type": "null" }],
                    "description": "protocol must be non-ethereum or undefined for non-EVM chains"
                  }
                }
              }
            }
          }
        }
      ]
    }
  }
}

=== pinax-network/supported-networks/public/TheGraphNetworksRegistry_v0_2_x.json
{
  "$schema": "https://graphregistry.pages.dev/TheGraphNetworksRegistrySchema_v0_2.json",
  "version": "0.2.13",
  "title": "The Graph networks registry",
  "description": "This registry was generated and validated. Do NOT edit it manually.",
  "updatedAt": "2024-11-07T15:09:05.499Z",
  "networks": [
    {
      "id": "mainnet",
      "shortName": "Ethereum",
      "fullName": "Ethereum Mainnet",
      "aliases": [
        "ethereum",
        "eth",
        "eth-mainnet",
        "evm-1"
      ],
      "caip2Id": "eip155:1",
      "graphNode": {
        "protocol": "ethereum"
      },
      "explorerUrls": [
        "https://etherscan.io"
      ],
      "rpcUrls": [
        "https://rpc.ankr.com/eth",
        "https://mainnet.infura.io/v3/{INFURA_API_KEY}"
      ],
      "apiUrls": [
        {
          "url": "https://api.etherscan.io/api",
          "kind": "etherscan"
        },
        {
          "url": "https://eth.blockscout.com/api",
          "kind": "blockscout"
        }
      ],
      "networkType": "mainnet",
      "support": {
        "subgraphs": [
          {
            "provider": "e&n"
          }
        ],
        "sps": [
          {
            "provider": "e&n"
          }
        ],
        "firehose": [
          {
            "provider": "pinax",
            "url": "eth.firehose.pinax.network:443"
          },
          {
            "provider": "streamingfast",
            "url": "mainnet.eth.streamingfast.io:443"
          }
        ],
        "substreams": [
          {
            "provider": "pinax",
            "url": "eth.substreams.pinax.network:443"
          },
          {
            "provider": "streamingfast",
            "url": "mainnet.eth.streamingfast.io:443"
          }
        ]
      },
      "issuanceRewards": true,
      "nativeToken": "ETH",
      "docsUrl": "https://ethereum.org/en/developers/docs/",
      "indexerDocsUrls": [
        {
          "url": "https://docs.infradao.com/archive-nodes-101/ethereum",
          "kind": "rpc"
        }
      ],
      "web3Icon": "ethereum",
      "genesis": {
        "hash": "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
        "height": 0
      },
      "firehose": {
        "blockType": "sf.ethereum.type.v2.Block",
        "evmExtendedModel": true,
        "bufUrl": "https://buf.build/streamingfast/firehose-ethereum",
        "bytesEncoding": "hex"
      }
    },
    {
      "id": "optimism",
      "shortName": "Optimism",
      "fullName": "OP Mainnet",
      "aliases": [
        "evm-10",
        "op-mainnet"
      ],
      "caip2Id": "eip155:10",
      "graphNode": {
        "protocol": "ethereum"
      },
      "relations": [
        {
          "kind": "l2Of",
          "network": "mainnet"
        }
      ],
      "explorerUrls": [
        "https://optimistic.etherscan.io/"
      ],
      "rpcUrls": [
        "https://mainnet.optimism.io",
        "https://optimism.drpc.org"
      ],
      "apiUrls": [
        {
          "url": "https://optimism.abi.pinax.network/api",
          "kind": "etherscan"
        }
      ],
      "support": {
        "subgraphs": [
          {
            "provider": "e&n"
          }
        ],
        "sps": [
          {
            "provider": "e&n"
          }
        ],
        "firehose": [
          {
            "provider": "streamingfast",
            "url": "opt-mainnet.streamingfast.io:443"
          }
        ],
        "substreams": [
          {
            "provider": "streamingfast",
            "url": "opt-mainnet.streamingfast.io:443"
          }
        ]
      },
      "networkType": "mainnet",
      "issuanceRewards": true,
      "nativeToken": "ETH",
      "docsUrl": "https://docs.optimism.io/",
      "indexerDocsUrls": [
        {
          "url": "https://docs.infradao.com/archive-nodes-101/optimism",
          "kind": "rpc"
        }
      ],
      "web3Icon": "optimistic-ethereum",
      "genesis": {
        "hash": "0x7ca38a1916c42007829c55e69d3e9a73265554b586a499015373241b8a3fa48b",
        "height": 0
      },
      "firehose": {
        "blockType": "sf.ethereum.type.v2.Block",
        "evmExtendedModel": false,
        "bufUrl": "https://buf.build/streamingfast/firehose-ethereum",
        "bytesEncoding": "hex"
      }
    },
    {
      "id": "gnosis",
      "shortName": "Gnosis",
      "fullName": "Gnosis Mainnet",
      "aliases": [
        "evm-100",
        "gnosis-mainnet"
      ],
      "caip2Id": "eip155:100",
      "graphNode": {
        "protocol": "ethereum"
      },
      "explorerUrls": [
        "https://gnosisscan.io",
        "https://gnosis.blockscout.com"
      ],
      "rpcUrls": [
        "https://rpc.gnosischain.com",
        "https://rpc.gnosis.gateway.fm",
        "https://rpc.ankr.com/gnosis"
      ],
      "apiUrls": [
        {
          "url": "https://gnosis.abi.pinax.network/api",
          "kind": "etherscan"
        }
      ],
      "support": {
        "subgraphs": [
          {
            "provider": "e&n"
          }
        ]
      },
      "networkType": "mainnet",
      "issuanceRewards": true,
      "nativeToken": "XDAI",
      "docsUrl": "https://docs.gnosischain.com",
      "indexerDocsUrls": [
        {
          "url": "https://docs.infradao.com/archive-nodes-101/gnosis",
          "kind": "rpc"
        }
      ],
      "web3Icon": "gnosis",
      "genesis": {
        "hash": "0x4f1dd23188aab3a76b463e4af801b52b1248ef073c648cbdc4c9333d3da79756",
        "height": 0
      },
      "firehose": {
        "blockType": "sf.ethereum.type.v2.Block",
        "evmExtendedModel": false,
        "bufUrl": "https://buf.build/streamingfast/firehose-ethereum",
        "bytesEncoding": "hex"
      }
    },
    {
      "id": "gnosis-chiado",
      "shortName": "Gnosis Chiado",
      "fullName": "Gnosis Chiado Testnet",
      "aliases": [
        "chiado"
      ],
      "caip2Id": "eip155:10200",
      "graphNode": {
        "protocol": "ethereum"
      },
      "explorerUrls": [
        "https://blockscout.chiadochain.net"
      ],
      "rpcUrls": [
        "https://rpc.chiadochain.net"
      ],
      "apiUrls": [
        {
          "url": "https://gnosis-chiado.blockscout.com/api",
          "kind": "etherscan"
        }
      ],
      "support": {
        "subgraphs": [
          {
            "provider": "e&n"
          }
        ]
      },
      "networkType": "testnet",
      "relations": [
        {
          "kind": "testnetOf",
          "network": "gnosis"
        }
      ],
      "issuanceRewards": false,
      "nativeToken": "XDAI",
      "docsUrl": "https://docs.gnosischain.com",
      "web3Icon": "gnosis",
      "genesis": {
        "hash": "0xada44fd8d2ecab8b08f256af07ad3e777f17fb434f8f8e678b312f576212ba9a",
        "height": 0
      },
      "firehose": {
        "blockType": "sf.ethereum.type.v2.Block",
        "evmExtendedModel": false,
        "bufUrl": "https://buf.build/streamingfast/firehose-ethereum",
        "bytesEncoding": "hex"
      }
    },
    {
      "id": "polygon-zkevm",
      "shortName": "Polygon zkEVM",
      "fullName": "Polygon zkEVM Mainnet",
      "aliases": [],
      "caip2Id": "eip155:1101",
      "graphNode": {
        "protocol": "ethereum"
      },
      "relations": [
        {
          "kind": "l2Of",
          "network": "mainnet"
        }
      ],
      "explorerUrls": [
        "https://zkevm.polygonscan.com"
      ],
      "rpcUrls": [
        "https://zkevm-rpc.com",
        "https://polygon-zkevm.drpc.org"
      ],
      "apiUrls": [
        {
          "url": "https://polygon-zkevm.abi.pinax.network/api",
          "kind": "etherscan"
        }
      ],
      "networkType": "mainnet",
      "support": {
        "subgraphs": [
          {
            "provider": "e&n"
          }
        ]
      },
      "issuanceRewards": false,
      "nativeToken": "ETH",
      "docsUrl": "https://polygon.technology/polygon-zkevm",
      "web3Icon": "polygon-zkevm",
      "genesis": {
        "hash": "0x81005434635456a16f74ff7023fbe0bf423abbc8a8deb093ffff455c0ad3b741",
        "height": 0
      },
      "firehose": {
        "blockType": "sf.ethereum.type.v2.Block",
        "evmExtendedModel": false,
        "bufUrl": "https://buf.build/streamingfast/firehose-ethereum",
        "bytesEncoding": "hex"
      }
    },
    {
      "id": "sepolia",
      "shortName": "Ethereum Sepolia",
      "fullName": "c",
      "aliases": [
        "evm-11155111"
      ],
      "caip2Id": "eip155:11155111",
      "networkType": "testnet",
      "relations": [
        {
          "kind": "testnetOf",
          "network": "mainnet"
        }
      ],
      "graphNode": {
        "protocol": "ethereum"
      },
      "explorerUrls": [
        "https://sepolia.etherscan.io/",
        "https://sepolia.otterscan.io"
      ],
      "rpcUrls": [
        "https://rpc.sepolia.org",
        "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
      ],
      "apiUrls": [],
      "support": {
        "subgraphs": [
          {
            "provider": "e&n"
          }
        ],
        "sps": [
          {
            "provider": "e&n"
          }
        ],
        "firehose": [
          {
            "provider": "pinax",
            "url": "sepolia.firehose.pinax.network:443"
          },
          {
            "provider": "streamingfast",
            "url": "sepolia.eth.streamingfast.io:443"
          }
        ],
        "substreams": [
          {
            "provider": "pinax",
            "url": "sepolia.substreams.pinax.network:443"
          },
          {
            "provider": "streamingfast",
            "url": "sepolia.eth.streamingfast.io:443"
          }
        ]
      },
      "issuanceRewards": false,
      "nativeToken": "ETH",
      "docsUrl": "https://sepolia.dev/",
      "genesis": {
        "hash": "0x25a5cc106eea7138acab33231d7160d69cb777ee0c2c553fcddf5138993e6dd9",
        "height": 0
      },
      "firehose": {
        "blockType": "sf.ethereum.type.v2.Block",
